# Site settings
title: Dicle Laundry
description: Diyarbakır Endüstriyel Kuru Temizleme
keywords: Endüstriyel Kuru Temizleme 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
